[package]

name = "ollama_code"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
reqwest = { version = "0.12.23", features = ["json"] }
tokio = { version = "1", features = ["full"] }     # optional: async runtime
